name: DallasRead.com
description: Dream. Risk. Win. Repeat.
markdown: kramdown
permalink: /:categories/:title

collections:
  category:
    output: true
  categories:
    sort_by: order
    output: true
